mainMenu:
  login: 'https://apps.mercdev.com/Account/LogOn'
  home: 'http://mercdev.com'
  company: 'http://mercdev.com/company'
  mobile: 'http://mercdev.com/mobile'
  macos: 'http://mercdev.com/macos'
  cloud: 'http://mercdev.com/cloud'
  blog: 'http://blog.mercdev.com/'

footerMenu:
  services:
    mobile: 'http://mercdev.com/mobile'
    macos: 'http://mercdev.com/macos'
    cloud: 'http://mercdev.com/cloud'
    academy: 'http://mercdev.com/company/academy'
  products:
    socialFramework: 'http://mercdev.com/product/social_framework'
    visualizationData: 'http://mercdev.com/product/visualization_data'
  support:
    applicationImageDesignGuidelines: 'http://mercdev.com/support/application-image-design-guidelines'
    runningiOSAdHocBuilds: 'http://mercdev.com/support/running-iOS-ad-hoc-builds'
    udid: 'http://mercdev.com/support/udid'
  company:
    about: 'http://mercdev.com/company/about'
    management: 'http://mercdev.com/company/management'
    requestEstimate: 'http://mercdev.com/company/request_estimate'
    clientList: 'http://mercdev.com/our_clients/client_list'
    salesExecutive: 'http://mercdev.com/company/sales_executive'
    blog: 'http://blog.mercdev.com/'

socialMenu:
  twitter: 'https://twitter.com/mercdev'
  facebook: 'http://www.facebook.com/mercdev'
  linkedin: 'http://www.linkedin.com/company/mercury-development-llc/'